name: Build Development IPA (No Signing)

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'capacitor.config.ts'

jobs:
  build-dev-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Sync Capacitor
      run: npx cap sync ios
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install CocoaPods
      run: |
        cd ios/App
        pod install
        
    - name: Update app info
      run: |
        cd ios/App/App
        # Get version from package.json
        VERSION=$(node -p "require('../../../package.json').version")
        BUILD_NUMBER=$(date +%Y%m%d%H%M%S)
        
        # Update Info.plist
        /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" Info.plist
        /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" Info.plist
        
        echo "App Version: $VERSION"
        echo "Build Number: $BUILD_NUMBER"
        
    - name: Build for simulator (no signing required)
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Debug \
          -destination 'generic/platform=iOS Simulator' \
          -archivePath AppSimulator.xcarchive \
          archive
          
    - name: Build for device (development signing)
      run: |
        cd ios/App
        # Try to build for device with automatic signing
        xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath App.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          archive || echo "Device build failed (expected without proper signing)"
          
    - name: Create unsigned IPA
      run: |
        cd ios/App
        # Create a basic export for testing (unsigned)
        mkdir -p export
        
        if [ -d "App.xcarchive" ]; then
          # Copy the app to export directory
          cp -r App.xcarchive/Products/Applications/App.app export/
          
          # Create a basic IPA structure
          mkdir -p export/Payload
          cp -r App.xcarchive/Products/Applications/App.app export/Payload/
          
          cd export
          zip -r ScanEats-Development-Unsigned.ipa Payload/
          
          echo "✅ Created unsigned development IPA"
          ls -la *.ipa
        else
          echo "❌ Archive not found, creating placeholder"
          echo "Build completed but archive failed" > export/build-log.txt
        fi
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ScanEats-iOS-Development
        path: |
          ios/App/export/*.ipa
          ios/App/export/*.app
          ios/App/export/*.txt
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: |
          ios/App/*.log
          ios/App/App.xcarchive/
        retention-days: 7
